# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [1]:
#your code here
import numpy as np
import pandas as pd
import matplotlib

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [2]:
def isValid(A,B):
  #your code here
  array1 = np.array(A)
  array2 = np.array(B)
  if array1.shape[1] == array2.shape[0] :
    print("Matrix multiplication is Valid")
  else :
    print("Invalid Input!")
  return isValid

##### (ii) Using loops (without using numpy)

In [3]:
def matrix_multiply(A,B):
  #your code here
  array1 = np.array(A)
  array2 = np.array(B)
  box = []
  for i in range(0,array1.shape[0]):
    for j in range(0,array2.shape[1]):
      y=0
      for k  in range(0,array1.shape[1]):
        x = array1[i,k]*array2[k,j]
        y = y+x
      boxes = box.append(y)
      j = j+1
    i = i+1
  array3 = np.array(box)
  array4 = array3.reshape(array1.shape[0],array2.shape[1])
  return array4


##### (iii) Using numpy

In [4]:
def matrix_multiply_2(A,B):
  #your code here
  array1 = np.array(A)
  array2 = np.array(B)
  new_matrix = array1 @ array2
  return new_matrix

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [6]:
def mean(x):
  #your code here
  x_bar = sum(x)/len(x)
  return x_bar

In [7]:
def standard_deviation(x):
  #your code here
  x_bar = sum(x)/len(x)
  c = x_bar**2
  b = 0
  for i in x:
    a = i**2
    b = b+a
  deviation = np.sqrt((b/(len(x)))-c)
  return deviation

In [8]:
def zscore_normalisation(x):
  #your code here
  u = float(mean(x))
  sigma = float(standard_deviation(x))
  result = []
  for i in x:
   new_x = (i-u)/sigma
   results = result.append(new_x)
  return result

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [9]:
def zscore_normalisation_2(x):
  #your code here
  A = np.array(x)
  u = np.mean(A)
  sigma = np.std(A)
  new_x = (x-u)/sigma
  return new_x

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [11]:
def sigmoidfn(x):
  #your code here
  sigmoid = 1/(1+np.exp(-x))
  return sigmoid

##### (ii) Write a fn to implement derivative of sigmoid fn

In [12]:
def derivative(x):
  #your code here
  sigmoid_derivative = (-np.exp(-x))/pow(1+np.exp(-x),2)
  return sigmoid_derivative

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [14]:
#your code here
df_old = pd.read_csv("superheated_vapor_properties.csv")
#data preprocessing
df_modified = df_old.drop_duplicates()
df = df_modified.drop([543,544,1088])
df.to_csv("modified_superheated_vapor_properties.csv",index = False)
#reading modified csv
df = pd.read_csv("modified_superheated_vapor_properties.csv")

### Display the shape of data frame


In [ ]:
#your code here
df.shape

### Return an array containing names of all the columns

In [ ]:
#your code here
df.columns.to_numpy()

### Display the number of null values in each column of the dataframe



In [ ]:
#your code here
df_null = df.isnull().sum()
print(df_null)

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
#your code here
df['Property at Pressure'] = df['Property']+' at '+ df['Pressure'].astype(str)
print('Enthalpy at 75kpa and 573 k:')
print(df[(df['Property'] == 'H') & (df['Pressure'] == 75)]['300'].values[0])
print('Entropy at 250kpa and 493 k:')
print(df[(df['Property'] == 'S') & (df['Pressure'] == 250)]['220'].values[0])

### Find out the column with the highest number of missing values

In [ ]:
#your code here
df_null = df.isnull().sum()
df_max = df_null.idxmax()
print(f"The column with max null values is: {df_max}")

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
#your code here
H = df.loc[df['Property'].str.contains('H')]
H_Data = pd.DataFrame(H)
mean_enthalpy = H_Data['Liq_Sat'].mean()
print(f"The average enthalpy of Sat. Liq. at all different pressures is: {mean_enthalpy}")

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here
V = df.loc[df['Property'].str.contains('V')]
U = df.loc[df['Property'].str.contains('U')]
H = df.loc[df['Property'].str.contains('H')]
S = df.loc[df['Property'].str.contains('S')]
V_Data = pd.DataFrame(V)
U_Data = pd.DataFrame(U)
H_Data = pd.DataFrame(H)
S_Data = pd.DataFrame(S)
display(V_Data,U_Data,H_Data,S_Data)

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*